server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

jwt:
  issuer: user-service
  access-token-ttl-min: 15
  refresh-token-ttl-days: 14
  secret: ${JWT_SECRET}
